FROM nginx:1.18-alpine
SHELL ["/bin/ash", "-oeux", "pipefail", "-c"]

RUN apk update && \
  mkdir -p /work/backend/public && \
  touch /work/backend/public/index.php

ARG DOMAIN

ENV TZ=Asia/Tokyo \
    DOMAIN=${DOMAIN}

RUN apk update
RUN cd /etc \
    mkdir letsencrypt/live/${DOMAIN}

COPY ./nginx_back/default.conf /etc/nginx/conf.d/default.conf

RUN export DOMAIN=${DOMAIN} 
RUN envsubst '$$DOMAIN'< /etc/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf

WORKDIR /work/backend/public